task_loader:
  _target_: tasks.FewShotTask
  wrapped_task: 
    _target_: tasks.Mbpp2Task2
  wrapped_split: ${wrapped_split}
  shots: ${task_shots}
  seed: ${task_loader_seed}


wrapped_split: transfer
task_shots: 10
task_loader_seed: 16

task_name: humaneval_${task_shots}shots
